---
- name: Freeradius system packages
  apt:
    name:
      - freeradius
      - freeradius-rest
    state: latest
  notify: restart freeradius

- name: Freeradius postgres packages
  when: openwisp2_database.engine == "django.contrib.gis.db.backends.postgis"
  apt:
    name: freeradius-postgresql
    state: latest
  notify: restart freeradius

- name: Freeradius mysql packages
  when: openwisp2_database.engine == "django.contrib.gis.db.backends.mysql"
  apt:
    name: freeradius-mysql
    state: latest
  notify: restart freeradius

- name: SQL configuration
  template:
    src: freeradius/sql.j2
    dest: "{{ freeradius_mods_available_dir }}/sql"
    mode: 0640
    owner: freerad
    group: freerad
  notify: restart freeradius

- name: Enable SQL module
  file:
    src: "{{ freeradius_mods_available_dir }}/sql"
    dest: "{{ freeradius_mods_enabled_dir }}/sql"
    state: link
    mode: 0640
    owner: freerad
    group: freerad

- name: adding user 'freerad' to www-data group for database access
  when: openwisp2_database.engine == "django.contrib.gis.db.backends.spatialite"
  user:
    name: freerad
    groups: www-data
    append: yes

- name: SQL Counter module
  template:
    src: freeradius/sql_counter.j2
    dest: "{{ freeradius_mods_available_dir }}/sql_counter"
    mode: 0640
    owner: freerad
    group: freerad
  notify: restart freeradius

- name: Enable SQL Counter module
  file:
    src: "{{ freeradius_mods_available_dir }}/sql_counter"
    dest: "{{ freeradius_mods_enabled_dir }}/sql_counter"
    state: link
    mode: 0640
    owner: freerad
    group: freerad

- name: Add Attributes to freeradius dictionary
  lineinfile:
    path: "{{ freeradius_dir }}/dictionary"
    line: "ATTRIBUTE      Expire-After         {{ freeradius_expire_attr_after_seconds }}    integer"

- name: REST configuration
  template:
    src: freeradius/rest.j2
    dest: "{{ freeradius_mods_available_dir }}/rest"
    mode: 0640
    owner: freerad
    group: freerad
  notify: restart freeradius

- name: Enable REST module
  file:
    src: "{{ freeradius_mods_available_dir }}/rest"
    dest: "{{ freeradius_mods_enabled_dir }}/rest"
    state: link
    mode: 0640
    owner: freerad
    group: freerad

- name: Remove default site
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - "{{ freeradius_sites_enabled_dir }}/default"
    - "{{ freeradius_sites_enabled_dir }}/inner-tunnel"

- name: Site configuration
  template:
    src: freeradius/openwisp_site.j2
    dest: "{{ freeradius_sites_enabled_dir }}/openwisp_site"
    mode: 0640
    owner: freerad
    group: freerad
  notify: restart freeradius
