---
- name: Freeradius additional mysql system packages
  when: openwisp2_radius and freeradius_sql.dialect == "mysql"
  apt:
    name:
      - freeradius-mysql
      - mariadb-server
    state: latest
  notify: start mysql

- name: Install pymysql
  when: openwisp2_radius and freeradius_sql.dialect == "mysql"
  pip:
    name: pymysql
    state: latest
  retries: 5
  delay: 10
  register: result
  until: result is success
  notify: start mysql

- name: start mysql for migration
  when: openwisp2_radius and freeradius_sql.dialect == "mysql"
  meta: flush_handlers

- name: Create freeradius database
  when: openwisp2_radius and freeradius_sql.dialect == "mysql"
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    db: "{{ freeradius_sql.dbname }}"
    state: present

- name: Create freeradius database user
  when: openwisp2_radius and freeradius_sql.dialect == "mysql"
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ freeradius_sql.user }}"
    password: "{{ freeradius_sql.password }}"
